dist: xenial

os:
    - linux
#    - osx 
#    - windows

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
        - BL_ADDON=io_scene_obj
    matrix:
        - BLENDER_VERSION="2.81a"
        - BLENDER_VERSION="2.82a"
        - BLENDER_VERSION="2.83"

language: python
python:
    - 3.7

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}

addons:
    apt:
        packages:
            - blender

before_install:
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}

install:
    - cd $TRAVIS_BUILD_DIR
    - python --version
    - pip install -r blender_requirements.txt
    - pip list

script:
    - cd ${TRAVIS_BUILD_DIR}
    #- make flake8
    #- flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - python ${TRAVIS_BUILD_DIR}/scripts/test_addon.py ${BL_ADDON} ${BLENDER_VERSION}
    
after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        on_success: change
        on_failure: always
